version: 2

jobs:
  build:
    working_directory: ~/gulmohar-server
    docker:
      - image: continuumio/miniconda3
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout # checkout source code to working directory
      - run: pip install -r broker_ubuntu.yml
      # - run: source activate mdbroker
      - run: 
          command: coverage run -m pytest
          name: Test
      - run:
          command: coverage report -m
          name: Coverage

