version: 2

jobs:
  build:
    working_directory: ~/gulmohar-server
    docker:
      - image: continuumio/miniconda3
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout # checkout source code to working directory
      - run: pip install -r broker_ubuntu.yml
      # - run: source activate mdbroker
      - run: 
          command: pytest
          name: Test




# version: 2.1

# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - pip install -r broker_ubuntu.yml
#       - python/save-cache
#       - run:
#           command: pytest
#           name: Test

# workflows:
#   main:
#     jobs:
#       - build-and-test
